import { assertSafeUrl } from '../../packages/protocol/security.js';
import { ShareError } from '../../packages/protocol/index.js';

/** Explicit overrides also support an isolated launch without installing a profile. */
export function codexOverrides(baseUrl: string, model: string): string[] {
  generateProfile(baseUrl, model); // Reuse the same strict input validation.
  return [
    `model=${JSON.stringify(model)}`, 'model_provider="friends_share"', 'web_search="disabled"',
    'model_providers.friends_share.name="Friends Share"',
    `model_providers.friends_share.base_url=${JSON.stringify(baseUrl.replace(/\/$/, ''))}`,
    'model_providers.friends_share.env_key="SHARE_TOKEN_ACCESS_KEY"',
    'model_providers.friends_share.wire_api="responses"',
    'model_providers.friends_share.requires_openai_auth=false',
    'model_providers.friends_share.supports_websockets=false',
    'model_providers.friends_share.supports_standalone_web_search=false',
    'model_providers.friends_share.request_max_retries=0',
    'model_providers.friends_share.stream_max_retries=0',
    'model_providers.friends_share.stream_idle_timeout_ms=300000',
    'shell_environment_policy.filters.SHARE_TOKEN_ACCESS_KEY="exclude"',
  ];
}

/** Pure generation: this never edits the user's existing Codex config. */
export function generateProfile(baseUrl: string, model: string): string {
  const url = assertSafeUrl(baseUrl);
  if (!['https:', 'http:'].includes(url.protocol)) throw new ShareError('SHARE_URL_INVALID', 'Codex 模型入口需要 HTTP(S) 地址。');
  if (!/^[a-zA-Z0-9][a-zA-Z0-9._:/-]{0,127}$/.test(model)) throw new ShareError('SHARE_MODEL_INVALID', '模型 ID 不符合格式要求。');
  const base = url.toString().replace(/\/$/, '');
  return `# Generated by Share Token. This profile contains no credentials.\n# Use only models and clients that have passed compatibility validation.\nmodel = ${JSON.stringify(model)}\nmodel_provider = "friends_share"\nweb_search = "disabled"\n\n[model_providers.friends_share]\nname = "Friends Share"\nbase_url = ${JSON.stringify(base)}\nenv_key = "SHARE_TOKEN_ACCESS_KEY"\nwire_api = "responses"\nrequires_openai_auth = false\nsupports_websockets = false\nsupports_standalone_web_search = false\nrequest_max_retries = 0\nstream_max_retries = 0\nstream_idle_timeout_ms = 300000\n\n# Keep the gateway credential out of model-launched shell processes.\n[shell_environment_policy.filters]\nSHARE_TOKEN_ACCESS_KEY = "exclude"\n`;
}
